version: '3.9'

services:
  web:
    build: .
    container_name: ficct-school
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000