# Generated by Django 5.2 on 2025-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_loggerservice_user_id_loggerservice_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggerservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Logger Service', 'verbose_name_plural': 'Logger Services'},
        ),
        migrations.AddField(
            model_name='loggerservice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
