# Generated by Django 5.2.1 on 2025-05-30 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_participation'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date_recorded', 'student', 'subject'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='grade',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Exam'), ('TASK', 'Task'), ('PROJECT', 'Project'), ('PARTICIPATION', 'Participation'), ('OTHER', 'Other')], default='EXAM', max_length=20)),
                ('date', models.DateField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='academic.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Assessment Item',
                'verbose_name_plural': 'Assessment Items',
                'ordering': ['trimester', 'date', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.assessmentitem'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assessment_item')},
        ),
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimesters', to='academic.period')),
            ],
            options={
                'verbose_name': 'Trimester',
                'verbose_name_plural': 'Trimesters',
                'ordering': ['period', 'start_date'],
                'unique_together': {('name', 'period')},
            },
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='trimester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='academic.trimester'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
