# Generated by Django 5.2.1 on 2025-05-31 23:47

import app.reports.models.bulletin_model
import base.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0005_alter_grade_options_rename_comments_grade_comment_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grades_data', models.JSONField(default=dict, help_text='Snapshot of grades and subject averages')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='authentication.student')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='academic.trimester')),
            ],
            options={
                'verbose_name': 'Student Bulletin',
                'verbose_name_plural': 'Student Bulletins',
                'ordering': ['-trimester__start_date', 'student__user__last_name'],
                'unique_together': {('student', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='BulletinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], max_length=10)),
                ('file', models.FileField(storage=base.storage.PublicMediaStorage(custom_path='bulletins'), upload_to=app.reports.models.bulletin_model.bulletin_file_upload_path)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.bulletin')),
            ],
            options={
                'verbose_name': 'Bulletin File',
                'verbose_name_plural': 'Bulletin Files',
                'ordering': ['bulletin', 'format'],
                'unique_together': {('bulletin', 'format')},
            },
        ),
    ]
