# Generated by Django 5.2.1 on 2025-06-01 00:00

import app.reports.models.bulletin_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinfile',
            name='file',
            field=models.FileField(upload_to=app.reports.models.bulletin_model.bulletin_file_upload_path),
        ),
    ]
