# Generated by Django 5.2.1 on 2025-06-01 00:40

import app.reports.models.bulletin_model
import base.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_bulletinfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinfile',
            name='file',
            field=models.FileField(storage=base.storage.PublicMediaStorage(custom_path='bulletins'), upload_to=app.reports.models.bulletin_model.bulletin_file_upload_path),
        ),
    ]
